=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'date'

module Marketcheck_api_sdk
  # Sales count query response
  class Sales
    # Sales count
    attr_accessor :counts

    # cpo sales count
    attr_accessor :cpo

    # Non-cpo sales count
    attr_accessor :non_cpo

    # inventory_type
    attr_accessor :inventory_type

    # Make
    attr_accessor :make

    # model
    attr_accessor :model

    # year
    attr_accessor :year

    # trim
    attr_accessor :trim

    # taxonomy_vin
    attr_accessor :taxonomy_vin

    # State
    attr_accessor :state

    # City
    attr_accessor :city

    # Days on market stats
    attr_accessor :dom_stats

    # Price stats
    attr_accessor :price_stats

    # Miles stats
    attr_accessor :miles_stats

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'counts' => :'counts',
        :'cpo' => :'cpo',
        :'non_cpo' => :'non-cpo',
        :'inventory_type' => :'inventory_type',
        :'make' => :'make',
        :'model' => :'model',
        :'year' => :'year',
        :'trim' => :'trim',
        :'taxonomy_vin' => :'taxonomy_vin',
        :'state' => :'state',
        :'city' => :'city',
        :'dom_stats' => :'dom_stats',
        :'price_stats' => :'price_stats',
        :'miles_stats' => :'miles_stats'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'counts' => :'Integer',
        :'cpo' => :'Integer',
        :'non_cpo' => :'Integer',
        :'inventory_type' => :'String',
        :'make' => :'String',
        :'model' => :'String',
        :'year' => :'String',
        :'trim' => :'String',
        :'taxonomy_vin' => :'String',
        :'state' => :'String',
        :'city' => :'String',
        :'dom_stats' => :'SalesStats',
        :'price_stats' => :'SalesStats',
        :'miles_stats' => :'SalesStats'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'counts')
        self.counts = attributes[:'counts']
      end

      if attributes.has_key?(:'cpo')
        self.cpo = attributes[:'cpo']
      end

      if attributes.has_key?(:'non-cpo')
        self.non_cpo = attributes[:'non-cpo']
      end

      if attributes.has_key?(:'inventory_type')
        self.inventory_type = attributes[:'inventory_type']
      end

      if attributes.has_key?(:'make')
        self.make = attributes[:'make']
      end

      if attributes.has_key?(:'model')
        self.model = attributes[:'model']
      end

      if attributes.has_key?(:'year')
        self.year = attributes[:'year']
      end

      if attributes.has_key?(:'trim')
        self.trim = attributes[:'trim']
      end

      if attributes.has_key?(:'taxonomy_vin')
        self.taxonomy_vin = attributes[:'taxonomy_vin']
      end

      if attributes.has_key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.has_key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.has_key?(:'dom_stats')
        self.dom_stats = attributes[:'dom_stats']
      end

      if attributes.has_key?(:'price_stats')
        self.price_stats = attributes[:'price_stats']
      end

      if attributes.has_key?(:'miles_stats')
        self.miles_stats = attributes[:'miles_stats']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          counts == o.counts &&
          cpo == o.cpo &&
          non_cpo == o.non_cpo &&
          inventory_type == o.inventory_type &&
          make == o.make &&
          model == o.model &&
          year == o.year &&
          trim == o.trim &&
          taxonomy_vin == o.taxonomy_vin &&
          state == o.state &&
          city == o.city &&
          dom_stats == o.dom_stats &&
          price_stats == o.price_stats &&
          miles_stats == o.miles_stats
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [counts, cpo, non_cpo, inventory_type, make, model, year, trim, taxonomy_vin, state, city, dom_stats, price_stats, miles_stats].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = Marketcheck_api_sdk.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
