=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'uri'

module Marketcheck_api_sdk
  class GraphsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Price, Miles plots data for given criteria
    # [DEPRECIATED Please check this in /search API using plot=true]Get price, miles plot data for active cars matching the given VIN's basic specification or Year, Make, Model, Trim (Optional) criteria
    # @param car_type Car type to get the scatter plot data for
    # @param [Hash] opts the optional parameters
    # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
    # @option opts [String] :vin VIN as a reference to the type of car for which plot data is to be returned
    # @option opts [String] :year Year of the car
    # @option opts [String] :make Make of the car
    # @option opts [String] :model Model of the Car
    # @option opts [String] :trim Trim of the Car
    # @option opts [String] :rows Number of results to return. Default is 1000. Max is 10000
    # @return [Array<PlotPoint>]
    def get_price_miles_plot_data(car_type, opts = {})
      data, _status_code, _headers = get_price_miles_plot_data_with_http_info(car_type, opts)
      data
    end

    # Price, Miles plots data for given criteria
    # [DEPRECIATED Please check this in /search API using plot&#x3D;true]Get price, miles plot data for active cars matching the given VIN&#39;s basic specification or Year, Make, Model, Trim (Optional) criteria
    # @param car_type Car type to get the scatter plot data for
    # @param [Hash] opts the optional parameters
    # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
    # @option opts [String] :vin VIN as a reference to the type of car for which plot data is to be returned
    # @option opts [String] :year Year of the car
    # @option opts [String] :make Make of the car
    # @option opts [String] :model Model of the Car
    # @option opts [String] :trim Trim of the Car
    # @option opts [String] :rows Number of results to return. Default is 1000. Max is 10000
    # @return [Array<(Array<PlotPoint>, Fixnum, Hash)>] Array<PlotPoint> data, response status code and response headers
    def get_price_miles_plot_data_with_http_info(car_type, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: GraphsApi.get_price_miles_plot_data ...'
      end
      # verify the required parameter 'car_type' is set
      if @api_client.config.client_side_validation && car_type.nil?
        fail ArgumentError, "Missing the required parameter 'car_type' when calling GraphsApi.get_price_miles_plot_data"
      end
      # resource path
      local_var_path = '/plots'

      # query parameters
      query_params = {}
      query_params[:'car_type'] = car_type
      query_params[:'api_key'] = opts[:'api_key'] if !opts[:'api_key'].nil?
      query_params[:'vin'] = opts[:'vin'] if !opts[:'vin'].nil?
      query_params[:'year'] = opts[:'year'] if !opts[:'year'].nil?
      query_params[:'make'] = opts[:'make'] if !opts[:'make'].nil?
      query_params[:'model'] = opts[:'model'] if !opts[:'model'].nil?
      query_params[:'trim'] = opts[:'trim'] if !opts[:'trim'].nil?
      query_params[:'rows'] = opts[:'rows'] if !opts[:'rows'].nil?

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = []
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'Array<PlotPoint>')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: GraphsApi#get_price_miles_plot_data\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
