=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'pry'

# Unit tests for Marketcheck_api_sdk::CRMApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CRMApi' do
  before do
    # run before each test
    @instance = Marketcheck_api_sdk::CRMApi.new
  end

  after do
    # run after each test
  end
  properties = {
    "vin" => %w[1N4AA5AP8EC477345],
    "sale_date" => %w[20180305 20180606]
  }
  opts = { 
    api_key: 'api key example', # String | The API Authentication Key. Mandatory with all API calls.
  }
  describe 'test an instance of CRMApi' do
    it 'should create an instance of CRMApi' do
      vin = properties["vin"][0]
      sale_date = properties["sale_date"][0]
      result = @instance.crm_check(vin, sale_date, opts)
      expect(result).not_to be_nil
      expect(result.for_sale).to be_truthy
      expect(@instance).to be_instance_of(Marketcheck_api_sdk::CRMApi)
    end
  end

  # unit tests for crm_check
  # CRM check of a particular vin
  # Check whether particular vin has had a listing after stipulated date or not
  # @param vin vin for which CRM check needs to be done
  # @param sale_date sale date after which listing has appeared or not
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @return [CRMResponse]
  describe 'crm_check test' do
    it 'should return false to crm test' do
      vin = properties["vin"][0]
      sale_date = properties["sale_date"][1]
      result = @instance.crm_check(vin, sale_date, opts)
      expect(result).not_to be_nil
      expect(result.for_sale).should false
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
