=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Marketcheck_api_sdk::GraphsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'GraphsApi' do
  before do
    # run before each test
    @instance = Marketcheck_api_sdk::GraphsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GraphsApi' do
    it 'should create an instance of GraphsApi' do
      expect(@instance).to be_instance_of(Marketcheck_api_sdk::GraphsApi)
    end
  end

  # unit tests for get_price_miles_plot_data
  # Price, Miles plots data for given criteria
  # [DEPRECIATED Please check this in /search API using plot&#x3D;true]Get price, miles plot data for active cars matching the given VIN&#39;s basic specification or Year, Make, Model, Trim (Optional) criteria
  # @param car_type Car type to get the scatter plot data for
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @option opts [String] :vin VIN as a reference to the type of car for which plot data is to be returned
  # @option opts [String] :year Year of the car
  # @option opts [String] :make Make of the car
  # @option opts [String] :model Model of the Car
  # @option opts [String] :trim Trim of the Car
  # @option opts [String] :rows Number of results to return. Default is 1000. Max is 10000
  # @return [Array<PlotPoint>]
  describe 'get_price_miles_plot_data test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
