=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'

# Unit tests for Marketcheck_api_sdk::VINDecoderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VINDecoderApi' do
  before do
    # run before each test
    @instance = Marketcheck_api_sdk::VINDecoderApi.new
  end

  after do
    # run after each test
  end
 properties = {
    "listing_id" => %w[4T1B11HK1JU643996-8a68ad13-7ca4-47eb-bc8f-53635b054667 4T1B11HK9JU644619-fe627386-1868-4b3f-9e64-0dd37e96a6c6]}
  
  describe 'test an instance of VINDecoderApi' do
    it 'should create an instance of VINDecoderApi' do
      properties["listing_id"].each{|id|
        
      }
      expect(@instance).to be_instance_of(Marketcheck_api_sdk::VINDecoderApi)
    end
  end

  # unit tests for decode
  # VIN Decoder
  # Get the basic information on specifications for a car identified by a valid VIN
  # @param vin VIN to decode
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @return [Build]
  describe 'decode test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_economy
  # Get Economy based on environmental factors
  # [MOCK] Calculate Economy i.e. Environmental Friendliness
  # @param vin VIN as a reference to the type of car for which Environmental Economy data is to be returned
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @return [Economy]
  describe 'get_economy test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_efficiency
  # Get fuel effeciency
  # [MOCK] Calculate fuel efficiency from taxonomy db mileage values
  # @param vin VIN as a reference to the type of car for which fuel data is to be returned
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @return [FuelEfficiency]
  describe 'get_efficiency test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_safety_rating
  # Get Safety Rating
  # [MOCK] Get Safety ratings from third party sources
  # @param vin VIN to fetch the safety ratings
  # @param [Hash] opts the optional parameters
  # @option opts [String] :api_key The API Authentication Key. Mandatory with all API calls.
  # @return [SafetyRating]
  describe 'get_safety_rating test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
