=begin
#Marketcheck Cars API

#<b>Access the New, Used and Certified cars inventories for all Car Dealers in US.</b> <br/>The data is sourced from online listings by over 44,000 Car dealers in US. At any time, there are about 6.2M searchable listings (about 1.9M unique VINs) for Used & Certified cars and about 6.6M (about 3.9M unique VINs) New Car listings from all over US. We use this API at the back for our website <a href='https://www.marketcheck.com' target='_blank'>www.marketcheck.com</a> and our Android and iOS mobile apps too.<br/><h5> Few useful links : </h5><ul><li>A quick view of the API and the use cases is depicated <a href='https://portals.marketcheck.com/mcapi/' target='_blank'>here</a></li><li>The Postman collection with various usages of the API is shared here https://www.getpostman.com/collections/2752684ff636cdd7bac2</li></ul>

OpenAPI spec version: 1.0.3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.0-SNAPSHOT

=end

# Common files
require 'Marketcheck_api_sdk/api_client'
require 'Marketcheck_api_sdk/api_error'
require 'Marketcheck_api_sdk/version'
require 'Marketcheck_api_sdk/configuration'

# Models
require 'Marketcheck_api_sdk/models/averages'
require 'Marketcheck_api_sdk/models/base_listing'
require 'Marketcheck_api_sdk/models/build'
require 'Marketcheck_api_sdk/models/crm_response'
require 'Marketcheck_api_sdk/models/comparison_point'
require 'Marketcheck_api_sdk/models/competitors_car_details'
require 'Marketcheck_api_sdk/models/competitors_point'
require 'Marketcheck_api_sdk/models/competitors_same_cars'
require 'Marketcheck_api_sdk/models/competitors_similar_cars'
require 'Marketcheck_api_sdk/models/dealer'
require 'Marketcheck_api_sdk/models/dealer_landing_page'
require 'Marketcheck_api_sdk/models/dealer_rating'
require 'Marketcheck_api_sdk/models/dealer_review'
require 'Marketcheck_api_sdk/models/dealers_response'
require 'Marketcheck_api_sdk/models/depreciation_point'
require 'Marketcheck_api_sdk/models/depreciation_stats'
require 'Marketcheck_api_sdk/models/economy'
require 'Marketcheck_api_sdk/models/error'
require 'Marketcheck_api_sdk/models/facet_item'
require 'Marketcheck_api_sdk/models/fuel_efficiency'
require 'Marketcheck_api_sdk/models/historical_listing'
require 'Marketcheck_api_sdk/models/listing'
require 'Marketcheck_api_sdk/models/listing_debug_attributes'
require 'Marketcheck_api_sdk/models/listing_extra_attributes'
require 'Marketcheck_api_sdk/models/listing_finance'
require 'Marketcheck_api_sdk/models/listing_lease'
require 'Marketcheck_api_sdk/models/listing_media'
require 'Marketcheck_api_sdk/models/listing_nest_extra_attributes'
require 'Marketcheck_api_sdk/models/listing_nest_media'
require 'Marketcheck_api_sdk/models/listing_vdp'
require 'Marketcheck_api_sdk/models/location'
require 'Marketcheck_api_sdk/models/make_model'
require 'Marketcheck_api_sdk/models/mds'
require 'Marketcheck_api_sdk/models/nest_dealer'
require 'Marketcheck_api_sdk/models/plot_point'
require 'Marketcheck_api_sdk/models/popularity_item'
require 'Marketcheck_api_sdk/models/rating_components'
require 'Marketcheck_api_sdk/models/review_components'
require 'Marketcheck_api_sdk/models/safety_rating'
require 'Marketcheck_api_sdk/models/sales'
require 'Marketcheck_api_sdk/models/sales_stats'
require 'Marketcheck_api_sdk/models/search_facets'
require 'Marketcheck_api_sdk/models/search_response'
require 'Marketcheck_api_sdk/models/search_stats'
require 'Marketcheck_api_sdk/models/stats_item'
require 'Marketcheck_api_sdk/models/trend_point'
require 'Marketcheck_api_sdk/models/vin_report'

# APIs
require 'Marketcheck_api_sdk/api/crm_api'
require 'Marketcheck_api_sdk/api/dealer_api'
require 'Marketcheck_api_sdk/api/facets_api'
require 'Marketcheck_api_sdk/api/graphs_api'
require 'Marketcheck_api_sdk/api/history_api'
require 'Marketcheck_api_sdk/api/inventory_api'
require 'Marketcheck_api_sdk/api/listings_api'
require 'Marketcheck_api_sdk/api/market_api'
require 'Marketcheck_api_sdk/api/vin_decoder_api'

module Marketcheck_api_sdk
  class << self
    # Customize default settings for the SDK using block.
    #   Marketcheck_api_sdk.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
